# 1739724965_793863_create_table_users.py
# Description: Create Table Users
# Generated by: dw_migrations
# Created on: 16.02.2025

# !!! Don't modify this variable !!!
timestamp = 1739724965.793863

# Migration up, modify here
sql_up = """
create table users
(
    id         int auto_increment,
    uuid       varchar(128)            null,
    email      varchar(128)            null,
    password   varchar(255)            null,
    created_at timestamp default now() not null,
    updated_at timestamp default now() not null on update now(),
    constraint users_pk primary key (id)
);
"""

# Migration down, modify here
sql_down = """
drop table if exists users;
"""